### ISSUE TITLE
Support for a dictionary of resources instead of just one

### ISSUE THREAD

**Issue by etsauer** [oybed/openshift-get-resources#1]
Could this role enhanced to accept a dictionary of lookups? Something like the following would be really valuable.

```
- hosts: servers
  gather_facts: false
  vars:
    openshift_get_resources:
      - key_name: namepsace_labels
        kind: service
        namespace: default
        label_selectors:
          - router = router 
      - key_name: infraid
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
        json_query: 'resources[0].status.infrastructureName'
  roles:
     - role: openshift-get-resources
```
